### ISSUE TITLE
Search is not working on Android.

### ISSUE THREAD

**Issue by ashu17706** [kiok46/duckduckgo#42]
Hey! I just came across this repo. Nice implementation Man! 
I just found that search is not working on Android Phones.

**Comment by kiok46** [comment]
Thanks @ashu17706 ,
It's using a sample data which is in [constants/data.json](https://github.com/kiok46/duckduckgo/blob/master/constants/data.json)

You can use DuckDuckGo's API or any other API api by updating the SearchList component from [here](https://github.com/kiok46/duckduckgo/blob/master/screens/StoriesScreen/StoriesList.js#L18) when [onSubmitEditingSearch](https://github.com/kiok46/duckduckgo/blob/master/components/SearchComponent.js#L85) gets called.

Showing the search results wasn't the main goal but the UI when building the app. But sure PR is welcome. :)

**Comment by kiok46** [comment]
Hi,
Added this in the readme: https://github.com/kiok46/duckduckgo#does-search-work
Closing this issue.

Have a great day 😸
