### ISSUE TITLE
can´not run this

### ISSUE THREAD

**Issue by jcpc91** [kiok46/duckduckgo#43]
hi!!
how i can run this project get error
if i run command npm start 
**>npm start**
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10

npm ERR! missing script: start
thanks

**Comment by kiok46** [comment]
Hi, this project was built using [expo](https://expo.io/).
Please do the following to run.

```
npm install exp --global
git clone https://github.com/kiok46/duckduckgo.git
cd duckduckgo
exp start
```

This will give you a URL and a QR code, you can use either to run the app devices or simulator (using Expo Client).

Thanks

**Comment by jcpc91** [comment]
@kiok46 thanks it works
