### ISSUE TITLE
why not expo ?

### ISSUE THREAD

**Issue by jpca999** [kiok46/duckduckgo#47]
I see that you built the final app on top of react-native & not Expo (though you provided a link for expo ), what challenges did you face while using expo ?

Id love to hear your thoughts.

**Comment by kiok46** [comment]
Hi @jpca999 
I have never really faced any issue when using expo, it's just that this application was quite outdated and I had to update it.

Expo mainly bugs me when I have to go native i.e writing native modules. see here https://docs.expo.io/versions/latest/guides/detach.html

I have created 2 separate branches. In the `master` branch you can run it via `react-native` and in the `expo-branch` you can run it via `expo`.

Please have a look at the updated readme https://github.com/kiok46/duckduckgo#how-to-run-via-expo
I love expo. 😄   I am closing this issue.
Have a great day 😺
