### ISSUE TITLE
unable to run project with rn

### ISSUE THREAD

**Issue by jpca999** [kiok46/duckduckgo#48]
![image](https://user-images.githubusercontent.com/1026325/32927122-eb875678-cb18-11e7-8fa0-0b410d1241dc.png)

Can you please provide a way to run this on expo ?

**Comment by kiok46** [comment]
Hi @jpca999 
Thanks for opening the issue. I was planning to make this change and I found the time today.
I have updated the readme, do have a look. https://github.com/kiok46/duckduckgo#how-to-run-via-expo
